name: Build Revit AddIn

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      Configuration: Release
      Platform: x64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SpaceTracker.sln

    - name: Build solution
      run: dotnet build SpaceTracker.sln --configuration ${{ env.Configuration }} --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: RevitAddIn
        path: '**/bin/${{ env.Configuration }}/'