name: 'Build .NET Framework 4.8.1 on Windows'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild (Visual Studio Build Tools)
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore SpaceTracker.sln

      - name: Build solution
        run: msbuild SpaceTracker.sln /p:Configuration=Release
